In [2]:
!pip install kaggle
import kaggle

WARNING: Ignoring invalid distribution ~oblib (C:\Users\iswar\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~oblib (C:\Users\iswar\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~oblib (C:\Users\iswar\anaconda3\Lib\site-packages)

Requirement already satisfied: kaggle in c:\users\iswar\anaconda3\lib\site-packages (2.0.2)
Requirement already satisfied: bleach in c:\users\iswar\anaconda3\lib\site-packages (from kaggle) (6.2.0)
Requirement already satisfied: jupytext in c:\users\iswar\anaconda3\lib\site-packages (from kaggle) (1.19.1)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in c:\users\iswar\anaconda3\lib\site-packages (from kaggle) (0.1.20)
Requirement already satisfied: packaging in c:\users\iswar\anaconda3\lib\site-packages (from kaggle) (24.2)
Requirement already satisfied: protobuf in c:\users\iswar\anaconda3\lib\site-packages (from kaggle) (3.20.3)
Requirement already satisfied: python-dateutil in c:\users\iswar\anaconda3\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in c:\users\iswar\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: requests in c:\users\iswar\anaconda3\lib\site-packages (from kaggle) (2.32.3)
Requirement already satisfied: tqdm in c:\users\iswar\anaconda3\lib\site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\iswar\anaconda3\lib\site-packages (from kaggle) (2.3.0)
Requirement already satisfied: webencodings in c:\users\iswar\anaconda3\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in c:\users\iswar\anaconda3\lib\site-packages (from jupytext->kaggle) (2.2.0)
Requirement already satisfied: mdit-py-plugins in c:\users\iswar\anaconda3\lib\site-packages (from jupytext->kaggle) (0.3.0)
Requirement already satisfied: nbformat in c:\users\iswar\anaconda3\lib\site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in c:\users\iswar\anaconda3\lib\site-packages (from jupytext->kaggle) (6.0.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\iswar\anaconda3\lib\site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.0)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\iswar\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (2.20.0)
Requirement already satisfied: jsonschema>=2.6 in c:\users\iswar\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (4.23.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\iswar\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.7.2)
Requirement already satisfied: traitlets>=5.1 in c:\users\iswar\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\iswar\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (24.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\iswar\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\iswar\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\iswar\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.22.3)
Requirement already satisfied: platformdirs>=2.5 in c:\users\iswar\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.3.7)
Requirement already satisfied: pywin32>=300 in c:\users\iswar\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (308)
Requirement already satisfied: six>=1.5 in c:\users\iswar\anaconda3\lib\site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\iswar\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\iswar\anaconda3\lib\site-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\iswar\anaconda3\lib\site-packages (from requests->kaggle) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\iswar\anaconda3\lib\site-packages (from requests->kaggle) (2026.1.4)
Requirement already satisfied: colorama in c:\users\iswar\anaconda3\lib\site-packages (from tqdm->kaggle) (0.4.6)
You must authenticate before you can call the Kaggle API.
Follow the instructions to authenticate at: https://github.com/Kaggle/kaggle-cli/blob/main/docs/README.md#authentication

NameError: name 'exit' is not defined

In [3]:
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading orders.csv.zip to C:\Users\iswar\SQL+Python

  0%|          | 0.00/200k [00:00<?, ?B/s]
100%|##########| 200k/200k [00:00<00:00, 311kB/s]
100%|##########| 200k/200k [00:00<00:00, 311kB/s]

In [4]:
import zipfile
zip_ref = zipfile.ZipFile('orders.csv.zip')
zip_ref.extractall()
zip_ref.close()

In [9]:
import pandas as  pd
df = pd.read_csv('orders.csv', na_values = ['Not Available','unknown'])
df.head(20)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3
10,11,2023-03-31,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,1470,1710,9,3
11,12,2023-12-25,NaN,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,750,910,4,3
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,20,20,3,3
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,360,410,3,2
14,15,2023-11-09,NaN,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,60,70,5,5
15,16,2022-06-18,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,OFF-BI-10000756,0,0,3,5
16,17,2022-02-04,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,OFF-ST-10004186,610,670,6,3
17,18,2023-08-04,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,OFF-ST-10000107,60,60,2,4
18,19,2022-01-23,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,OFF-AR-10003056,10,10,2,4
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,170,210,3,3

In [10]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [15]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [17]:
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [20]:
df['discount'] = df['list_price'] * df['discount_percent']*0.01

In [22]:
df['sale_price'] = df['list_price'] - df['discount']

In [25]:
df['profit'] = df['sale_price'] - df['cost_price']
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [27]:
df.dtypes

order_id              int64
order_date           object
ship_mode            object
segment              object
country              object
city                 object
state                object
postal_code           int64
region               object
category             object
sub_category         object
product_id           object
cost_price            int64
list_price            int64
quantity              int64
discount_percent      int64
discount            float64
sale_price          float64
profit              float64
dtype: object

In [28]:
df['order_date']= pd.to_datetime(df['order_date'],format = '%Y-%m-%d')

In [30]:
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale_price                 float64
profit                     float64
dtype: object

In [36]:
df.drop(columns=['list_price','cost_price','discount_percent'],inplace = True)

In [37]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\iswar\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: pymysql in c:\users\iswar\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\iswar\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\iswar\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)

WARNING: Ignoring invalid distribution ~oblib (C:\Users\iswar\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~oblib (C:\Users\iswar\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~oblib (C:\Users\iswar\anaconda3\Lib\site-packages)

In [38]:
import sqlalchemy as sal
engine = sal.create_engine('mysql+pymysql://root:mysql123@localhost:3306/orders')
conn = engine.connect()

In [39]:
df.to_sql('df_orders',con = conn, index = False, if_exists=  'append')

9994